
/* Drop Tables */

DROP TABLE TM_ITEM CASCADE CONSTRAINTS;
DROP TABLE TM_META CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE TM_ITEM
(
	-- 기관코드
	ORG_CODE char(3) NOT NULL,
	PRIMARY KEY (ORG_CODE)
);


CREATE TABLE TM_META
(
	-- 기관코드
	ORG_C char(3) NOT NULL,
	-- 메타코드
	META_C varchar2(30) NOT NULL,
	META_NAME varchar2(100),
	CONSTRAINT TM_META_PK PRIMARY KEY (ORG_C, META_C)
);



/* Comments */

COMMENT ON COLUMN TM_ITEM.ORG_CODE IS '기관코드';
COMMENT ON COLUMN TM_META.ORG_C IS '기관코드';
COMMENT ON COLUMN TM_META.META_C IS '메타코드';



